name: Build and push image dotnet

on:
  workflow_dispatch: {}

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Build and validate
        run: |
          echo "docker build"
          docker build -t mi-app:1.0.0 .  
          docker images
          echo "docker ps"
          docker ps
          echo "docker run"
          docker run -d --name mi-contenedor -p 8080:8080 mi-app:1.0.0
          echo "docker ps II"
          docker ps
          


